# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
    adapter: mysql2
    database: rails_chat
    username: root
    password: 19930220
    pool: 5
    host: localhost
    encoding: utf8
    timeout: 5000

development:
    adapter: mysql2
    database: rails_chat
    username: root
    password: 19930220
    pool: 5
    host: localhost
    encoding: utf8
    timeout: 5000

test:
    adapter: mysql2
    database: rails_chat
    username: root
    password: 19930220
    pool: 5
    host: localhost
    encoding: utf8
    timeout: 5000

production:
    adapter: mysql2
    database: rails_chat
    username: root
    password: 19930220
    pool: 5
    host: localhost
    encoding: utf8
    timeout: 5000